import dotenv from "dotenv";

dotenv.config();

export const META = {
	CLIENT_ID: process.env.META_CLIENT_ID!,
	CLIENT_SECRET: process.env.META_CLIENT_SECRET!,
	REDIRECT_URI: process.env.META_REDIRECT_URI!,
};

export const FIREBASE = {
	AUTH_DOMAIN: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN!,
	API_KEY: process.env.NEXT_PUBLIC_FIREBASE_API_KEY!,
	PROJECT_ID: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID!,
	STORAGE_BUCKET: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET!,
	MESSAGING_SENDER_ID: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID!,
	APP_ID: process.env.NEXT_PUBLIC_FIREBASE_APP_ID!,
	MEASUREMENT_ID: process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID!,
};

export const FIREBASE_ADMIN = {
	TYPE: process.env.NEXT_PUBLIC_FIREBASE_TYPE!,
	PROJECT_ID: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID!,
	PRIVATE_KEY_ID: process.env.NEXT_PUBLIC_FIREBASE_PRIVATE_KEY_ID!,
	PRIVATE_KEY: process.env.NEXT_PUBLIC_FIREBASE_PRIVATE_KEY!,
	CLIENT_EMAIL: process.env.NEXT_PUBLIC_FIREBASE_CLIENT_EMAIL!,
	CLIENT_ID: process.env.NEXT_PUBLIC_FIREBASE_CLIENT_ID!,
	AUTH_URI: process.env.NEXT_PUBLIC_FIREBASE_AUTH_URI!,
	TOKEN_URI: process.env.NEXT_PUBLIC_FIREBASE_TOKEN_URI!,
	AUTH_PROVIDER_X509_CERT_URL:
		process.env.NEXT_PUBLIC_FIREBASE_AUTH_PROVIDER_X509_CERT_URL!,
	CLIENT_X509_CERT_URL: process.env.NEXT_PUBLIC_FIREBASE_CLIENT_X509_CERT_URL!,
	UNIVERSE_DOMAIN: process.env.NEXT_PUBLIC_FIREBASE_UNIVERSE_DOMAIN!,
};
